=== jasdeepkhalsa/sikher-gurbani-searcher/python/notes/xml2/bani.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="xmlGurbani">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="information" />
				<xs:element ref="book" />
			</xs:sequence>
			<xs:attribute name="book" use="required" type="xs:NCName" />
			<xs:attribute name="language" use="required" type="xs:NCName" />
			<xs:attribute name="status" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NCName">
						<xs:enumeration value="complete" />
						<xs:enumeration value="incomplete" />
						<xs:enumeration value="empty" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="translation" />
						<xs:enumeration value="transliteration" />
						<xs:enumeration value="gurbani" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="version" use="required" type="xs:decimal" />
		</xs:complexType>
	</xs:element>
	<xs:element name="information">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="author" />
				<xs:element ref="date" />
				<xs:element ref="description" />
				<xs:element ref="language" />
				<xs:element ref="type" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="author" type="xs:string" />
	<xs:element name="date" type="xs:NMTOKEN" />
	<xs:element name="description" type="xs:string" />
	<xs:element name="language" type="xs:string" />
	<xs:element name="type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Translation" />
				<xs:enumeration value="Transliteration" />
				<xs:enumeration value="Gurbani" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="book">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="page" />
			</xs:sequence>
			<xs:attribute name="number" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	<xs:element name="page">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="hymn" />
			</xs:sequence>
			<xs:attribute name="number" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	<xs:element name="hymn">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="line" />
			</xs:sequence>
			<xs:attribute name="author" use="required" type="xs:integer" />
			<xs:attribute name="melody" use="required" type="xs:integer" />
			<xs:attribute name="number" use="required" type="xs:integer" />
			<xs:attribute name="house" use="optional" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	<xs:element name="line">
		<xs:complexType mixed="true">
			<xs:attribute name="lnumber" use="required" type="xs:integer" />
			<xs:attribute name="number" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jasdeepkhalsa/sikher-gurbani-searcher/python/notes/xml2/xxxx.template.xx.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Please read the readme.txt before using this file -->
<xmlGurbani xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bani.xsd" book="sggsj" language="en" version="1.0" status="empty" type="transliteration">
	<information>
		<author>Your Name</author>
		<date>YYYY-MM-DD</date>
		<description>A Description</description>
		<language>A Language e.g. English</language>
		<type>Transliteration</type>
		<!-- Type must be either <type>Gurbani</type>
						  or	 <type>Translation</type>
						  or	 <type>Transliteration</type> -->
	</information>
	<book number="1">
		<page number="1">
			<hymn number="1" author="1" melody="1">
				<line number="1" lnumber="1">ik ounkaar sath naam kuruthaa purukh nirubho niruvair akaal moorath ajoonee saibhun gur prusaadh</line>
				<line number="2" lnumber="3">jap</line>
				<line number="3" lnumber="4">aadh such jugaadh such</line>
				<line number="4" lnumber="4">hai bhee such naanuk hosee bhee such</line>
				<line number="5" lnumber="5">sochai soch n hovee jae sochee lukh vaar</line>
				<line number="6" lnumber="5">chupai chup n hovee jae laae rehaa liv thaar</line>
 				<line number="7" lnumber="5">bhukhiaa bhukh n outhuree jae bunnaa pureeaa bhaar</line>
				<line number="8" lnumber="6">sehus siaanupaa lukh hohi th eik n chulai naal</line>
				<line number="9" lnumber="6">kiv sachiaaraa hoeeai kiv koorrai thuttai paal</line>
				<line number="10" lnumber="7">hukam rujaaee chulunaa naanuk likhiaa naal</line>
			</hymn>
			<hymn number="2" author="1" melody="1">
				<line number="1" lnumber="7">hukumee hovan aakaar hukum n kehiaa jaaee</line>
				<line number="2" lnumber="8">hukumee hovan jeea hukam milai vaddiaaee</line>
				<line number="3" lnumber="8">hukumee outhum neech hukam likh dhukh sukh paaeeahi</line>
				<line number="4" lnumber="9">eikunaa hukumee bukhusees eik hukumee sudhaa bhuvaaeeahi</line>
				<line number="5" lnumber="9">hukumai andhar subh ko baahar hukum n koe</line>
				<line number="6" lnumber="10">naanuk hukumai jae bujhai th houmai kehai n koe</line>
			</hymn>
			<hymn number="3" author="1" melody="1">
				<line number="1" lnumber="10">gaavai ko thaan hovai kisai thaan</line>
				<line number="2" lnumber="11">gaavai ko dhaath jaanai neesaan</line>
				<line number="3" lnumber="11">gaavai ko gun vaddiaaeeaa chaar</line>
				<line number="4" lnumber="11">gaavai ko vidhiaa vikhum veechaar</line>
				<line number="5" lnumber="12">gaavai ko saaj kurae thun khaeh</line>
				<line number="6" lnumber="12">gaavai ko jeea lai fir dhaeh</line>
				<line number="7" lnumber="12">gaavai ko jaapai dhisai dhoor</line>
			</hymn>
		</page>
	</book>
</xmlGurbani>

<!-- Don't forget to check:
		(1) All tags are closed
		(2) The document is valid
		(3) The document is well formed
		(4) The language used is an ISO code e.g. pa-IN or en or en-US etc.
		(5) You save this file in the format book.type.language.version.xml -->

<!-- Thank you for doing this selfless service for humanity! -->

=== jasdeepkhalsa/sikher-gurbani-searcher/java/build/data/sggsj.translation.en.2.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="xmlgurbani.css" type="text/css"?>
<xmlGurbani xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="bani.xsd"
	book="sggsj" language="en-US" version="3.0" status="incomplete" type="translation">
    <information>
        <author>Sant Singh Khalsa</author>
        <date>2005-08-16</date>
        <description>This is the latest and most complete and accurate translation of Guru Granth Sahib.</description>
        <language>English: United States</language>
        <type>Translation</type>
    </information>
    <book number="1">
        <page number="1">
            <hymn number="1" author="1" melody="1">
                <line number="1" lnumber="1">One Universal Creator God. The Name Is Truth. Creative Being Personified. No Fear. No Hatred. Image Of The Undying, Beyond Birth, Self-Existent. By Guru's Grace ~</line>
                <line number="2" lnumber="3">Chant And Meditate:</line>
                <line number="3" lnumber="4">True In The Primal Beginning. True Throughout The Ages.</line>
                <line number="4" lnumber="4">True Here And Now. O Nanak, Forever And Ever True. ||1||</line>
                <line number="5" lnumber="5">By thinking, He cannot be reduced to thought, even by thinking hundreds of thousands of times.</line>
                <line number="6" lnumber="5">By remaining silent, inner silence is not obtained, even by remaining lovingly absorbed deep within.</line>
                <line number="7" lnumber="5">The hunger of the hungry is not appeased, even by piling up loads of worldly goods.</line>
                <line number="8" lnumber="6">Hundreds of thousands of clever tricks, but not even one of them will go along with you in the end.</line>
                <line number="9" lnumber="6">So how can you become truthful? And how can the veil of illusion be torn away?</line>
                <line number="10" lnumber="7">O Nanak, it is written that you shall obey the Hukam of His Command, and walk in the Way of His Will. ||1||</line>
            </hymn>
            <hymn number="2" author="1" melody="1">
                <line number="11" lnumber="7">By His Command, bodies are created; His Command cannot be described.</line>
                <line number="12" lnumber="8">By His Command, souls come into being; by His Command, glory and greatness are obtained.</line>
                <line number="13" lnumber="8">By His Command, some are high and some are low; by His Written Command, pain and pleasure are obtained.</line>
                <line number="14" lnumber="9">Some, by His Command, are blessed and forgiven; others, by His Command, wander aimlessly forever.</line>
                <line number="15" lnumber="9">Everyone is subject to His Command; no one is beyond His Command.</line>
                <line number="16" lnumber="10">O Nanak, one who understands His Command, does not speak in ego.  ||2||</line>
            </hymn>
            <hymn number="3" author="1" melody="1">
                <line number="17" lnumber="10">Some sing of His Power-who has that Power?</line>
                <line number="18" lnumber="11">Some sing of His Gifts, and know His Sign and Insignia.</line>
                <line number="19" lnumber="11">Some sing of His Glorious Virtues, Greatness and Beauty.</line>
                <line number="20" lnumber="11">Some sing of knowledge obtained of Him, through difficult philosophical studies.</line>
                <line number="21" lnumber="12">Some sing that He fashions the body, and then again reduces it to dust.</line>
                <line number="22" lnumber="12">Some sing that He takes life away, and then again restores it.</line>
                <line number="23" lnumber="12">Some sing that He seems so very far away.</line>
            </hymn>
        </page>
        <page number="2">
            <hymn number="4" author="1" melody="1">
                <line number="1" lnumber="1">One Universal Creator God. The Name Is Truth. Creative Being Personified. No Fear. No Hatred. Image Of The Undying, Beyond Birth, Self-Existent. By Guru's Grace ~</line>
                <line number="2" lnumber="3">Chant And Meditate:</line>
                <line number="3" lnumber="4">True In The Primal Beginning. True Throughout The Ages.</line>
                <line number="4" lnumber="4">True Here And Now. O Nanak, Forever And Ever True. ||1||</line>
                <line number="5" lnumber="5">By thinking, He cannot be reduced to thought, even by thinking hundreds of thousands of times.</line>
                <line number="6" lnumber="5">By remaining silent, inner silence is not obtained, even by remaining lovingly absorbed deep within.</line>
                <line number="7" lnumber="5">The hunger of the hungry is not appeased, even by piling up loads of worldly goods.</line>
                <line number="8" lnumber="6">Hundreds of thousands of clever tricks, but not even one of them will go along with you in the end.</line>
                <line number="9" lnumber="6">So how can you become truthful? And how can the veil of illusion be torn away?</line>
                <line number="10" lnumber="7">O Nanak, it is written that you shall obey the Hukam of His Command, and walk in the Way of His Will. ||1||</line>
            </hymn>
            <hymn number="5" author="1" melody="1">
                <line number="11" lnumber="7">By His Command, bodies are created; His Command cannot be described.</line>
                <line number="12" lnumber="8">By His Command, souls come into being; by His Command, glory and greatness are obtained.</line>
                <line number="13" lnumber="8">By His Command, some are high and some are low; by His Written Command, pain and pleasure are obtained.</line>
                <line number="14" lnumber="9">Some, by His Command, are blessed and forgiven; others, by His Command, wander aimlessly forever.</line>
                <line number="15" lnumber="9">Everyone is subject to His Command; no one is beyond His Command.</line>
                <line number="16" lnumber="10">O Nanak, one who understands His Command, does not speak in ego.  ||2||</line>
            </hymn>
            <hymn number="6" author="1" melody="1">
                <line number="17" lnumber="10">Some sing of His Power-who has that Power?</line>
                <line number="18" lnumber="11">Some sing of His Gifts, and know His Sign and Insignia.</line>
                <line number="19" lnumber="11">Some sing of His Glorious Virtues, Greatness and Beauty.</line>
                <line number="20" lnumber="11">Some sing of knowledge obtained of Him, through difficult philosophical studies.</line>
                <line number="21" lnumber="12">Some sing that He fashions the body, and then again reduces it to dust.</line>
                <line number="22" lnumber="12">Some sing that He takes life away, and then again restores it.</line>
                <line number="23" lnumber="12">Some sing that He seems so very far away.</line>
            </hymn>
        </page>

    </book>
</xmlGurbani>

=== jasdeepkhalsa/sikher-gurbani-searcher/java/build/data/sggsj.gurbani.pa.3.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="xmlgurbani.css" type="text/css"?>
<xmlGurbani xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="bani.xsd"
	book="sggsj" language="pa-IN" version="3.0" status="incomplete" type="gurbani">
    <information>
        <author>Unknown</author>
        <date>2005-08-16</date>
        <description>This is the latest and most complete version of the Shri Guru Granth Sahib Ji to date.</description>
        <language>Gurmukhi</language>
        <type>Gurbani</type>
    </information>
    <book number="1">
        <page number="1">
            <hymn number="1" author="1" melody="1">
                <line number="1" lnumber="1">ੴ ਸਤਿ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ਨਿਰਭਉ ਨਿਰਵੈਰੁ ਅਕਾਲ ਮੂਰਤਿ ਅਜੂਨੀ ਸੈਭੰ ਗੁਰ ਪ੍ਰਸਾਦਿ ॥</line>
                <line number="2" lnumber="3">॥ ਜਪੁ ॥</line>
                <line number="3" lnumber="4">ਆਦਿ ਸਚੁ ਜੁਗਾਦਿ ਸਚੁ ॥</line>
                <line number="4" lnumber="4">ਹੈ ਭੀ ਸਚੁ ਨਾਨਕ ਹੋਸੀ ਭੀ ਸਚੁ ॥੧॥</line>
                <line number="5" lnumber="5">ਸੋਚੈ ਸੋਚਿ ਨ ਹੋਵਈ ਜੇ ਸੋਚੀ ਲਖ ਵਾਰ ॥</line>
                <line number="6" lnumber="5">ਚੁਪੈ ਚੁਪ ਨ ਹੋਵਈ ਜੇ ਲਾਇ ਰਹਾ ਲਿਵ ਤਾਰ ॥</line>
                <line number="7" lnumber="5">ਭੁਖਿਆ ਭੁਖ ਨ ਉਤਰੀ ਜੇ ਬੰਨਾ ਪੁਰੀਆ ਭਾਰ ॥</line>
                <line number="8" lnumber="6">ਸਹਸ ਸਿਆਣਪਾ ਲਖ ਹੋਹਿ ਤ ਇਕ ਨ ਚਲੈ ਨਾਲਿ ॥</line>
                <line number="9" lnumber="6">ਕਿਵ ਸਚਿਆਰਾ ਹੋਈਐ ਕਿਵ ਕੂੜੈ ਤੁਟੈ ਪਾਲਿ ॥</line>
                <line number="10" lnumber="7">ਹੁਕਮਿ ਰਜਾਈ ਚਲਣਾ ਨਾਨਕ ਲਿਖਿਆ ਨਾਲਿ ॥੧॥</line>
            </hymn>
            <hymn number="2" author="1" melody="1">
                <line number="11" lnumber="7">ਹੁਕਮੀ ਹੋਵਨਿ ਆਕਾਰ ਹੁਕਮੁ ਨ ਕਹਿਆ ਜਾਈ ॥</line>
                <line number="12" lnumber="8">ਹੁਕਮੀ ਹੋਵਨਿ ਜੀਅ ਹੁਕਮਿ ਮਿਲੈ ਵਡਿਆਈ ॥</line>
                <line number="13" lnumber="8">ਹੁਕਮੀ ਉਤਮੁ ਨੀਚੁ ਹੁਕਮਿ ਲਿਖਿ ਦੁਖ ਸੁਖ ਪਾਈਅਹਿ ॥</line>
                <line number="14" lnumber="9">ਇਕਨਾ ਹੁਕਮੀ ਬਖਸੀਸ ਇਕਿ ਹੁਕਮੀ ਸਦਾ ਭਵਾਈਅਹਿ ॥</line>
                <line number="15" lnumber="9">ਹੁਕਮੈ ਅੰਦਰਿ ਸਭੁ ਕੋ ਬਾਹਰਿ ਹੁਕਮ ਨ ਕੋਇ ॥</line>
                <line number="16" lnumber="10">ਨਾਨਕ ਹੁਕਮੈ ਜੇ ਬੁਝੈ ਤ ਹਉਮੈ ਕਹੈ ਨ ਕੋਇ ॥੨॥</line>
            </hymn>
            <hymn number="3" author="1" melody="1">
                <line number="17" lnumber="10">ਗਾਵੈ ਕੋ ਤਾਣੁ ਹੋਵੈ ਕਿਸੈ ਤਾਣੁ ॥</line>
                <line number="18" lnumber="11">ਗਾਵੈ ਕੋ ਦਾਤਿ ਜਾਣੈ ਨੀਸਾਣੁ ॥</line>
                <line number="19" lnumber="11">ਗਾਵੈ ਕੋ ਗੁਣ ਵਡਿਆਈਆ ਚਾਰ ॥</line>
                <line number="20" lnumber="11">ਗਾਵੈ ਕੋ ਵਿਦਿਆ ਵਿਖਮੁ ਵੀਚਾਰੁ ॥</line>
                <line number="21" lnumber="12">ਗਾਵੈ ਕੋ ਸਾਜਿ ਕਰੇ ਤਨੁ ਖੇਹ ॥</line>
                <line number="22" lnumber="12">ਗਾਵੈ ਕੋ ਜੀਅ ਲੈ ਫਿਰਿ ਦੇਹ ॥</line>
                <line number="23" lnumber="12">ਗਾਵੈ ਕੋ ਜਾਪੈ ਦਿਸੈ ਦੂਰਿ ॥</line>
            </hymn>
        </page>
        <page number="2">
            <hymn number="4" author="1" melody="1">
                <line number="1" lnumber="1">ੴ ਸਤਿ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ਨਿਰਭਉ ਨਿਰਵੈਰੁ ਅਕਾਲ ਮੂਰਤਿ ਅਜੂਨੀ ਸੈਭੰ ਗੁਰ ਪ੍ਰਸਾਦਿ ॥</line>
                <line number="2" lnumber="3">॥ ਜਪੁ ॥</line>
                <line number="3" lnumber="4">ਆਦਿ ਸਚੁ ਜੁਗਾਦਿ ਸਚੁ ॥</line>
                <line number="4" lnumber="4">ਹੈ ਭੀ ਸਚੁ ਨਾਨਕ ਹੋਸੀ ਭੀ ਸਚੁ ॥੧॥</line>
                <line number="5" lnumber="5">ਸੋਚੈ ਸੋਚਿ ਨ ਹੋਵਈ ਜੇ ਸੋਚੀ ਲਖ ਵਾਰ ॥</line>
                <line number="6" lnumber="5">ਚੁਪੈ ਚੁਪ ਨ ਹੋਵਈ ਜੇ ਲਾਇ ਰਹਾ ਲਿਵ ਤਾਰ ॥</line>
                <line number="7" lnumber="5">ਭੁਖਿਆ ਭੁਖ ਨ ਉਤਰੀ ਜੇ ਬੰਨਾ ਪੁਰੀਆ ਭਾਰ ॥</line>
                <line number="8" lnumber="6">ਸਹਸ ਸਿਆਣਪਾ ਲਖ ਹੋਹਿ ਤ ਇਕ ਨ ਚਲੈ ਨਾਲਿ ॥</line>
                <line number="9" lnumber="6">ਕਿਵ ਸਚਿਆਰਾ ਹੋਈਐ ਕਿਵ ਕੂੜੈ ਤੁਟੈ ਪਾਲਿ ॥</line>
                <line number="10" lnumber="7">ਹੁਕਮਿ ਰਜਾਈ ਚਲਣਾ ਨਾਨਕ ਲਿਖਿਆ ਨਾਲਿ ॥੧॥</line>
            </hymn>
            <hymn number="5" author="1" melody="1">
                <line number="11" lnumber="7">ਹੁਕਮੀ ਹੋਵਨਿ ਆਕਾਰ ਹੁਕਮੁ ਨ ਕਹਿਆ ਜਾਈ ॥</line>
                <line number="12" lnumber="8">ਹੁਕਮੀ ਹੋਵਨਿ ਜੀਅ ਹੁਕਮਿ ਮਿਲੈ ਵਡਿਆਈ ॥</line>
                <line number="13" lnumber="8">ਹੁਕਮੀ ਉਤਮੁ ਨੀਚੁ ਹੁਕਮਿ ਲਿਖਿ ਦੁਖ ਸੁਖ ਪਾਈਅਹਿ ॥</line>
                <line number="14" lnumber="9">ਇਕਨਾ ਹੁਕਮੀ ਬਖਸੀਸ ਇਕਿ ਹੁਕਮੀ ਸਦਾ ਭਵਾਈਅਹਿ ॥</line>
                <line number="15" lnumber="9">ਹੁਕਮੈ ਅੰਦਰਿ ਸਭੁ ਕੋ ਬਾਹਰਿ ਹੁਕਮ ਨ ਕੋਇ ॥</line>
                <line number="16" lnumber="10">ਨਾਨਕ ਹੁਕਮੈ ਜੇ ਬੁਝੈ ਤ ਹਉਮੈ ਕਹੈ ਨ ਕੋਇ ॥੨॥</line>
            </hymn>
            <hymn number="6" author="1" melody="1">
                <line number="17" lnumber="10">ਗਾਵੈ ਕੋ ਤਾਣੁ ਹੋਵੈ ਕਿਸੈ ਤਾਣੁ ॥</line>
                <line number="18" lnumber="11">ਗਾਵੈ ਕੋ ਦਾਤਿ ਜਾਣੈ ਨੀਸਾਣੁ ॥</line>
                <line number="19" lnumber="11">ਗਾਵੈ ਕੋ ਗੁਣ ਵਡਿਆਈਆ ਚਾਰ ॥</line>
                <line number="20" lnumber="11">ਗਾਵੈ ਕੋ ਵਿਦਿਆ ਵਿਖਮੁ ਵੀਚਾਰੁ ॥</line>
                <line number="21" lnumber="12">ਗਾਵੈ ਕੋ ਸਾਜਿ ਕਰੇ ਤਨੁ ਖੇਹ ॥</line>
                <line number="22" lnumber="12">ਗਾਵੈ ਕੋ ਜੀਅ ਲੈ ਫਿਰਿ ਦੇਹ ॥</line>
                <line number="23" lnumber="12">ਗਾਵੈ ਕੋ ਜਾਪੈ ਦਿਸੈ ਦੂਰਿ ॥</line>
            </hymn>
        </page>
    </book>
</xmlGurbani>

=== jasdeepkhalsa/sikher-gurbani-searcher/java/build/data/sggsj.transliteration.en.3.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="xmlgurbani.css" type="text/css"?>
<xmlGurbani xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="bani.xsd"
	book="sggsj" language="en" version="1.0" status="incomplete" type="transliteration">
    <information>
        <author>Sukhjinder Sidhu</author>
        <date>2005-12-22</date>
        <description>This is a perfect phonetic transliteration created using Unicode mappings.</description>
        <language>English</language>
        <type>Transliteration</type>
    </information>
    <book number="1">
        <page number="1">
            <hymn number="1" author="1" melody="1">
                <line number="1" lnumber="1">ik ōuṅkāṛ sat nām karatā purakh nirabhau niravair akāl mūrat ajūnī saibhaṅ gur prasād ॥</line>
                <line number="2" lnumber="3">॥ jap ॥</line>
                <line number="3" lnumber="4">ād sach jugād sach ॥</line>
                <line number="4" lnumber="4">hai bhī sach nānak hōsī bhī sach ॥1॥</line>
                <line number="5" lnumber="5">sōchai sōch na hōvaī jē sōchī lakh vār ॥</line>
                <line number="6" lnumber="5">chupai chup na hōvaī jē lāi rahā liv tār ॥</line>
                <line number="7" lnumber="5">bhukhiā bhukh na utarī jē baṅnā purīā bhār ॥</line>
                <line number="8" lnumber="6">sahas siāṇapā lakh hōh ta ik na chalai nāl ॥</line>
                <line number="9" lnumber="6">kiv sachiārā hōīai kiv kūṛai tuṭai pāl ॥</line>
                <line number="10" lnumber="7">hukam rajāī chalaṇā nānak likhiā nāl ॥1॥</line>
            </hymn>
            <hymn number="2" author="1" melody="1">
                <line number="11" lnumber="7">hukamī hōvan ākār hukam na kahiā jāī ॥</line>
                <line number="12" lnumber="8">hukamī hōvan jī hukam milai vaḍiāī ॥</line>
                <line number="13" lnumber="8">hukamī utam nīch hukam likh dukh sukh pāīah ॥</line>
                <line number="14" lnumber="9">ikanā hukamī bakhasīs ik hukamī sadā bhavāīah ॥</line>
                <line number="15" lnumber="9">hukamai aṅdar sabh kō bāhar hukam na kōi ॥</line>
                <line number="16" lnumber="10">nānak hukamai jē bujhai ta haumai kahai na kōi ॥2॥</line>
            </hymn>
            <hymn number="3" author="1" melody="1">
                <line number="17" lnumber="10">gāvai kō tāṇ hōvai kisai tāṇ ॥</line>
                <line number="18" lnumber="11">gāvai kō dāt jāṇai nīsāṇ ॥</line>
                <line number="19" lnumber="11">gāvai kō guṇ vaḍiāīā chār ॥</line>
                <line number="20" lnumber="11">gāvai kō vidiā vikham vīchār ॥</line>
                <line number="21" lnumber="12">gāvai kō sāj karē tan khēh ॥</line>
                <line number="22" lnumber="12">gāvai kō jī lai phir dēh ॥</line>
                <line number="23" lnumber="12">gāvai kō jāpai disai dūr ॥</line>
            </hymn>
        </page>
        <page number="2">
            <hymn number="4" author="1" melody="1">
                <line number="1" lnumber="1">ik ōuṅkāṛ sat nām karatā purakh nirabhau niravair akāl mūrat ajūnī saibhaṅ gur prasād ॥</line>
                <line number="2" lnumber="3">॥ jap ॥</line>
                <line number="3" lnumber="4">ād sach jugād sach ॥</line>
                <line number="4" lnumber="4">hai bhī sach nānak hōsī bhī sach ॥1॥</line>
                <line number="5" lnumber="5">sōchai sōch na hōvaī jē sōchī lakh vār ॥</line>
                <line number="6" lnumber="5">chupai chup na hōvaī jē lāi rahā liv tār ॥</line>
                <line number="7" lnumber="5">bhukhiā bhukh na utarī jē baṅnā purīā bhār ॥</line>
                <line number="8" lnumber="6">sahas siāṇapā lakh hōh ta ik na chalai nāl ॥</line>
                <line number="9" lnumber="6">kiv sachiārā hōīai kiv kūṛai tuṭai pāl ॥</line>
                <line number="10" lnumber="7">hukam rajāī chalaṇā nānak likhiā nāl ॥1॥</line>
            </hymn>
            <hymn number="5" author="1" melody="1">
                <line number="11" lnumber="7">hukamī hōvan ākār hukam na kahiā jāī ॥</line>
                <line number="12" lnumber="8">hukamī hōvan jī hukam milai vaḍiāī ॥</line>
                <line number="13" lnumber="8">hukamī utam nīch hukam likh dukh sukh pāīah ॥</line>
                <line number="14" lnumber="9">ikanā hukamī bakhasīs ik hukamī sadā bhavāīah ॥</line>
                <line number="15" lnumber="9">hukamai aṅdar sabh kō bāhar hukam na kōi ॥</line>
                <line number="16" lnumber="10">nānak hukamai jē bujhai ta haumai kahai na kōi ॥2॥</line>
            </hymn>
            <hymn number="6" author="1" melody="1">
                <line number="17" lnumber="10">gāvai kō tāṇ hōvai kisai tāṇ ॥</line>
                <line number="18" lnumber="11">gāvai kō dāt jāṇai nīsāṇ ॥</line>
                <line number="19" lnumber="11">gāvai kō guṇ vaḍiāīā chār ॥</line>
                <line number="20" lnumber="11">gāvai kō vidiā vikham vīchār ॥</line>
                <line number="21" lnumber="12">gāvai kō sāj karē tan khēh ॥</line>
                <line number="22" lnumber="12">gāvai kō jī lai phir dēh ॥</line>
                <line number="23" lnumber="12">gāvai kō jāpai disai dūr ॥</line>
            </hymn>
        </page>

    </book>
</xmlGurbani>
